services:
  opentelemtryapi:
    image: ${DOCKER_REGISTRY-}opentelemtryapi
    build:
      context: .
      dockerfile: OpenTelemtryApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemtryapi.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - ConnectionStrings__DefaultConnection=Host=opentelemetryapi-postgres;Database=opentelemtryapi;Username=postgres;Password=postgres
    ports:
      - "5050:8080" 

  opentelemtryapi.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 20000:18888

  opentelemetryapi-postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: opentelemtryapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432